# NUMPY

In [ ]:
# numpy - Numerical Python
# Computation and procession of a 1D or multidimensional array
# Numpy is fastest library because it is written in C
# Collection of homogenous data. you can not have multiple data types in array

In [1]:
# How to check if numpy is installed
!pip install numpy

In [2]:
import numpy as np

### Creating of Numpy

In [3]:
# 1. List, tuple

lst = [1,2,3,4]

a = np.array(lst)
print(a, type(a))

[1 2 3 4] <class 'numpy.ndarray'>


In [10]:
a

array([1, 2, 3, 4])

In [60]:
b = np.array([['scbjdc'], ['bjkeddfe']])
print(b, type(b))

[['scbjdc']
 ['bjkeddfe']] <class 'numpy.ndarray'>


In [11]:
b

array('abc, efg, efrf, efef', dtype='<U20')

In [ ]:
#dimension - number of rows and columns

# Scaler --> Having only 1 value. for scaler dimesnion is 0

# Vector --> Have multiple values but no rows and columns

#2D --> Have Rows and columns

#3D --> Rows, columns and depth

In [12]:
lst = [1,2,3,4]

a = np.array(lst)

a.ndim   # 1 dimesnional

1

In [13]:
#Size - Number of elements in array
a.size

4

In [14]:
# Shape --> will give rows and columns but if it is a vector then it is same as size with a comma

a.shape 

# (4,) --> It means it is a vector

(4,)

In [22]:
# Dimension, shape and size of a scaler value
b = np.array(1)
print(b.ndim)
print(b.size)
print(b.shape)

0
1
()


In [23]:
# Dimension, shape and size of a vector value
lst = [1,2,3,4,5]
c = np.array(lst)
print(c.ndim)
print(c.size)
print(c.shape)

1
5
(5,)


In [24]:
# Dimension, shape and size of a 2D array
lst = [[1,2], [3,4], [5,6]]
d = np.array(lst)
print(d.ndim)
print(d.size)
print(d.shape)

2
6
(3, 2)


In [25]:
# Dimension, shape and size of a 3D array
lst = [[[1,2], [3,4], [5,6]], [[7,8], [9,0], [2,3]]]
e = np.array(lst)
print(e.ndim)
print(e.size)
print(e.shape)

3
12
(2, 3, 2)


In [29]:
# arange --> array of a range

r1 = np.arange(10)           #--> This will give an array of value from 0 to 9
r2 = np.arange(3,10,2)

print(r1)
print(r2)

[0 1 2 3 4 5 6 7 8 9]
[3 5 7 9]


In [31]:
#linspace --> Linear space

np.linspace(1,10,20) # 1 to 10 in 20 equal divison and 1 and 10 is inclusive

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [32]:
#Zeros

np.zeros(10)   #--> Array of ten elements with 0 value. 0. --> float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
a = np.zeros((4,5,3))
print(a.ndim)
print(a.size)
print(a.shape)

3
60
(4, 5, 3)


In [3]:
#zeros_like --> Replace values by 0 in a given array
import numpy as np
lst = [[[1,2], [3,4], [5,6]], [[7,8], [9,0], [2,3]]]
a = np.array(lst)
b = np.zeros_like(a)
print(b)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


In [4]:
ary = np.ones((3,4))
ary1 = np.zeros_like(ary)
print(ary1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [47]:
#ones
b = np.ones(10)
c = np.ones((5,2))
d = np.ones((5,2,3))
print(b)
print('*****')
print(c)
print('*****')
print(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
*****
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
*****
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
# Identity Matrix

# n * n  --> Rows and columns should be same

# Diagnoal is 1

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#Random

np.random.rand(4,3)    # values only from 0 to 1 will come, it will be random value always. 4x3 is Row x column

array([[0.96686739, 0.1649058 , 0.74527957],
       [0.77028474, 0.29724132, 0.18514607],
       [0.46344787, 0.15795619, 0.06638916],
       [0.96430023, 0.56190283, 0.27494779]])

In [34]:
# Random int

np.random.randint(6, 20, (4,5))   # Low is 5 inclusive, high is 20 exclusive 4,5 is row and column respectively 

array([[ 8, 11,  8, 13, 10],
       [16,  7,  9, 15, 19],
       [12, 13, 14,  8, 16],
       [ 8, 14, 13,  7,  6]])

### Change the shape of array

In [36]:
a = np.arange(6)
print(a)
print(a.shape)
#dimesnion --> 1
#size --> 6
# Shape --> 6

[0 1 2 3 4 5]
(6,)


In [37]:
# reshape()

# multiplication of rows and columns given in reshape should be equal to size of array to be reshaped. 

# for e.g for a array of size 6, following are possibilities

# 2 x 3
# 3 x 2
# 1 x 6
# 6 x 1

# 9 x 2 not possible as it require 18 elements.
a = np.arange(6)
a1 = a.reshape(2,3)
print(a1)
print()
a2 = a.reshape(3,2)
print(a2)
print()
a3 = a.reshape(1,6)
print(a3)
print()
a4 = a.reshape(6,1)
print(a4)
print()

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]

[[0 1 2 3 4 5]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]



In [39]:
np.arange(25).reshape(1,5,5)  #---> 3D matrix
np.arange(25).reshape(5,5,1)
np.arange(25).reshape(5,1,5)

# All above are correct

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [52]:
# inferred --> Program will calculate columns itself

#wherever we write -1 in reshape, program will calculate that value by itself

# -1 Can only be used once in reshape.

# 2D array
c = np.arange(125).reshape(25, -1)   # 25 rows are given. -1 will indicate program to calculate columns itself
print(c)

# 3D array
e = np.arange(125).reshape(-1, 5, 1)
print(e)

In [55]:
# Transpose of array convert rows into column and column into rows of a given matrix

# a = m * n
# b = n * m

# b is transpose Matrix of a

a1 = np.arange(18).reshape(6,-1)
print(a1)
print(a1.shape)
print()
a2 = a1.T
print(a2)
print(a2.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
(6, 3)

[[ 0  3  6  9 12 15]
 [ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]]
(3, 6)


In [68]:
asian_country = np.array([['india', 'china', 'nepal', 'srilanka', 'bhutan', 'hongkong'], ['india', 'china', 'nepal', 'srilanka', 'bhutan', 'hongkong']])
#asian_country
asian_country.shape

(2, 6)

In [71]:
a = asian_country.reshape(3, -1)
print(a)
print()
print(a.T)
# dtype='<U8 --> It means all strings length are less then equal to 8

[['india' 'china' 'nepal' 'srilanka']
 ['bhutan' 'hongkong' 'india' 'china']
 ['nepal' 'srilanka' 'bhutan' 'hongkong']]

[['india' 'bhutan' 'nepal']
 ['china' 'hongkong' 'srilanka']
 ['nepal' 'india' 'bhutan']
 ['srilanka' 'china' 'hongkong']]


In [93]:
# Ravel --> convert nd array into 1D

ac = np.array(['india', 'china', 'nepal', 'srilanka', 'bhutan', 'hongkong'])
print(ac)
print()
a = ac.reshape(2,3,1)
print(a)
print()
print(a.shape)   #--> (6,)
print()
d = a.ravel()
print(d)

['india' 'china' 'nepal' 'srilanka' 'bhutan' 'hongkong']

[[['india']
  ['china']
  ['nepal']]

 [['srilanka']
  ['bhutan']
  ['hongkong']]]

(2, 3, 1)

['india' 'china' 'nepal' 'srilanka' 'bhutan' 'hongkong']


In [ ]:
# attribute - No brackets
# method () - function call

### Basic operations on array

In [ ]:
# Elementwise 

In [94]:
# arithematic operation elementwise

a = np.array([10,20,30,40])
b = np.array([50,60,70,80])

a + b

array([ 60,  80, 100, 120])

In [95]:
a - b

array([-40, -40, -40, -40])

In [96]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [98]:
a//b

array([0, 0, 0, 0], dtype=int32)

In [99]:
a<30

array([ True,  True, False, False])

In [100]:
a>30

array([False, False, False,  True])

In [101]:
a*b   #--> This is elementwise multiplication

array([ 500, 1200, 2100, 3200])

In [ ]:
# Elemtwise multiplication and dot matrix multiplication

In [106]:
# dot product muliplication

a = np.arange(12).reshape(4,3)
b = np.random.randint(5, 15, (3,5))

print(a)
print()
print(a.shape)

print()
print(b)
print()
print(b.shape)
print()

c = a.dot(b)
print(c)
print()
print(c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

(4, 3)

[[13  5  7  6  7]
 [ 8 10 14  7 11]
 [ 5  9  7 14  5]]

(3, 5)

[[ 18  28  28  35  21]
 [ 96 100 112 116  90]
 [174 172 196 197 159]
 [252 244 280 278 228]]

(4, 5)


In [108]:
aay = np.array([10,90,110,190])

# Sum of all values of array
print(aay.sum())


# minimum of all values of array
print(aay.min())


# maximum of all values of array
print(aay.max())

400
10
190


In [110]:
num = np.arange(24).reshape(4,6)
print(num)
print()
print(num.sum())
# This will give sum of all value of matrix but how to find sum of rows only or column only. 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

276


In [114]:
# 1 --> Rows

# 2 --> columns

num = np.arange(24).reshape(4,6)
print(num)
print()
print(num.sum(axis=1))   # Vector of sum of rows
print()
print(num.sum(axis=0))   # Vector of sum of columns
print()
print(num.min(axis=1))   # Vector of min of rows
print()
print(num.min(axis=0))   # Vector of min of columns
print()
print(num.max(axis=1))   # Vector of max of rows
print()
print(num.max(axis=0))   # Vector of max of columns

print(num.sum(axis =1).min()) # This will give the minimum value from a array which is sum of all rows

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[ 15  51  87 123]

[36 40 44 48 52 56]

[ 0  6 12 18]

[0 1 2 3 4 5]

[ 5 11 17 23]

[18 19 20 21 22 23]
15


In [116]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]


In [119]:
# To get log value of any number
np.log([1,1,1,1])  # Log of 1 is 0

array([0., 0., 0., 0.])

In [122]:
# To get Sqrt
np.sqrt([4,9,16,25])

array([2., 3., 4., 5.])

In [123]:
# to get square
np.square([1,2,3,4])

array([ 1,  4,  9, 16], dtype=int32)

In [124]:
np.sin([90, 0, 180])

array([ 0.89399666,  0.        , -0.80115264])

#### Mean = Average

In [ ]:
Mean of 1,2,3,4 = (1+2+3+4)/4 =2.5

#### Median = Arrange value in ascending and then middle value. if it is even quantity then average of middle two

In [ ]:
Median of 3,2,4,5,1 --> 1,2,3,4,5 Median = 3
median of 3,2,5,4  --> 2,3,4,5 median = (3+4)/2 = 3.5

#### Mode = Most occured Value

In [126]:
a = np.array([10,20,30,4])
print(a.mean())
print(np.median(a))

16.0
15.0


### Indexing and Slicing in array

In [9]:
import numpy as np

b = np.array([[1,2,3], [4,5,6]])

In [4]:
#Indexing is same as in list

b[1][-1]  # --> 6

6

In [11]:
# Other way of indexing in array is 
b[1,-1]

6

In [13]:
a1 = np.arange(25).reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
#Indexing of array
a1[1:3,2:4]     

# 1:3 --> Row 1 and 2

# 2:4 --> Column 2 and 3

#This indexing will always give result in form of array

array([[ 7,  8],
       [12, 13]])

In [17]:
a1[:,2:4]

# :, --> It means all rows

# 2:4 --> Start column = 2 and stop column = 4

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [18]:
a1[2:,2:4]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [19]:
a1[:,1]  

# : --> All rows

# 1 --> Only column 1

array([ 1,  6, 11, 16, 21])

In [20]:
a1[::2,2::2]

# ::2 --> start = 0 stop = 5, step = 2 of rows

# 2::2 --> Strt = 2, stop = 5, step = 2 of columns

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [22]:
a1 = np.arange(36).reshape(4,-1)
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [23]:
# To find the number of elements less than 8
np.sum(a1<8)

8

In [24]:
a1<8

array([[ True,  True,  True,  True,  True,  True,  True,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [2]:
import numpy as np
a1 = np.random.randint(5, 1000, (100, 50))
print(np.sum(a1>8))

4976


In [5]:
a1 = np.random.randint(5, 1000, (10, 13))
a1

array([[582, 120, 304,  53, 634, 114, 418, 345,  81, 118, 293, 175, 292],
       [837, 324, 647, 690, 415, 805, 790, 466, 894, 306, 470,  74, 469],
       [340, 314, 101, 810, 793, 240, 225, 410, 243, 470, 245, 677, 781],
       [563, 391, 988, 705,  32, 879, 288, 749, 744, 147, 276, 730, 769],
       [253,  41, 483, 156, 167, 867, 192, 711, 895, 569,  99, 956,  17],
       [673, 730, 996, 345, 741, 807, 972, 685,  39, 668,  14, 254,  19],
       [400, 994, 510, 485, 928, 850, 953, 839, 230, 312, 956,  45, 189],
       [ 88, 164, 720, 726, 410, 845, 602, 188, 986, 153, 852,  51, 470],
       [181, 191, 161, 109, 989, 774, 116, 269, 403, 222,  67, 500, 991],
       [434, 877, 249, 368, 514, 983, 460, 953, 165,  96, 648, 571, 515]])

In [59]:
a = np.array([[582, 120, 304,  53],
       [837, 324, 647, 690],
       [340, 314, 101, 810],
       [563, 391, 988, 705],
       [253,  41, 483, 156],
       [673, 730, 996, 345],
       [400, 994, 510, 485],
       [ 88, 164, 720, 726],
       [181, 191, 161, 109],
       [434, 877, 249, 368]])

#print(np.sum(a>50, axis = 0))   #It will check number of elements greater than 50 in each column as axis = 0
print(np.sum(a>50, axis = 1))   #It will check number of elements greater than 50 in each row as axis = 1
a>50

[4 4 4 4 3 4 4 4 4 4]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
# Any

#Is there any number greater/less than 8

print(np.any(a<8))
print(np.any(a<50, axis = 1))
print(np.any(a<50, axis = 0))

False
[False False False  True  True  True  True False False False]
[False  True False False  True False False False  True False  True  True
  True]


In [15]:
# all

# Is all number greater or less than 8 ?

print(np.all(a<8))
print(np.all(a>25, axis = 1))
print(np.all(a>25, axis = 0))

False
[ True  True  True  True False False  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True False  True
 False]


In [16]:
# Iterating in an array

a = np.array([1,2,3,4,5])

for i in a:
    print(i)

1
2
3
4
5


In [18]:
a = np.array([[1,2,3,4], [5,4,2,32]])
for i in a:
    print(i)

[1 2 3 4]
[ 5  4  2 32]


In [17]:
a = np.array([[1,2,3,4], [5,4,2,32]])
# Nested list---> so nested loop to be used
for i in a:
    for j in i:
        print(j) 

1
2
3
4
5
4
2
32


In [19]:
# We can do above thing without using two for loop.

# For that we need to flaten the array...so we can use ravel/flatten function

a = np.array([[1,2,3,4], [5,4,2,32]])

for i in a.ravel():
    print(i)

1
2
3
4
5
4
2
32


In [20]:
# Flatten is same as ravel. Flatten is more famous among coders.

a = np.array([[1,2,3,4], [5,4,2,32]])

for i in a.flatten():
    print(i)

1
2
3
4
5
4
2
32


In [ ]:
a = np.array([[1,12,31,34], [50,42,52,32]])

for i in a.flatten():   # By default order = c
    print(i)
    
# Order 'C' means first Rows will come then column    
    

In [26]:
a = np.array([[1,12,31,34], [50,42,52,32]])
print(a.flatten(order = 'f'))
# for i in a.flatten(order = 'f'):   # By default order = f
#     print(i)
# Order 'F' means first COlumns then row will come

[ 1 50 12 42 31 52 34 32]


In [29]:
#nditer

a = np.array([[1,12,31,34], [50,42,52,32]])

for i in np.nditer(a, order ='f'):
    print(i)

1
50
12
42
31
52
34
32


In [33]:
# Splitting of array
a = np.array([[1,12,31,34], [50,42,52,32]])
print(np.split(a,2))


[array([[ 1, 12, 31, 34]]), array([[50, 42, 52, 32]])]


In [35]:
# Split in equal parts. Below array has 8 elements
# If i divide in 4 equal parts then each part will have 8/4 = 2 elements
a = np.array([1,12,31,34,50,42,52,32])
print(np.split(a,4))

[array([ 1, 12]), array([31, 34]), array([50, 42]), array([52, 32])]


In [36]:
# To split array by indexing.

a = np.array([1,12,31,34,50,42,12,34,76,52,32])

print(np.split(a, [2, 5, 7]))

# [array([ 1, 12]), array([31, 34, 50]), array([42, 12]), array([34, 76, 52, 32])]
#positions 0 to 2           2 to 5              5 to 7            7 to till end           

[array([ 1, 12]), array([31, 34, 50]), array([42, 12]), array([34, 76, 52, 32])]


### Vector Stacking-Concatenating of two arrays

In [39]:
import numpy as np

In [43]:
a = np.array([["Delhi", "Bhiwani"], ["amritsar", "kota"]])
b = np.array([["Noida", "Gurgaon"], ["Surat", "Mumbai"]])

#["Delhi", "Bhiwani"], 
#["amritsar", "kota"]
#        +                             This is axis = 0
# ["Noida", "Gurgaon"],
# ["Surat", "Mumbai"]    

#["Delhi", "Bhiwani"],      ["Noida", "Gurgaon"]
#                        +                        This is axis = 1
#["amritsar", "kota"]       ["Surat", "Mumbai"] 

print(np.concatenate((a,b)))  # By default axis = 0 means rowise
print()
print(np.concatenate((a,b), axis = 1)) # axis = 1 means columnwise

[['Delhi' 'Bhiwani']
 ['amritsar' 'kota']
 ['Noida' 'Gurgaon']
 ['Surat' 'Mumbai']]

[['Delhi' 'Bhiwani' 'Noida' 'Gurgaon']
 ['amritsar' 'kota' 'Surat' 'Mumbai']]


In [45]:
np.random.randint(5,100,(3,3))

array([[34, 81, 66],
       [28, 25, 50],
       [ 8, 50, 62]])

In [48]:
a = np.array([[54, 14, 45],
       [97, 22, 65],
       [47, 56, 30]])
b = np.array([[34, 81, 66],
       [28, 25, 50],
       [ 8, 50, 62]])
print(np.concatenate((a,b)))
print()
print(np.concatenate((a,b), axis = 1))

[[54 14 45]
 [97 22 65]
 [47 56 30]
 [34 81 66]
 [28 25 50]
 [ 8 50 62]]

[[54 14 45 34 81 66]
 [97 22 65 28 25 50]
 [47 56 30  8 50 62]]


## Axis 0 and 1 can be different for different function

In [ ]:
# Stack ---In place of axis stack can be used
# vstack --> columnwise
# hstack --> Rowwise

In [60]:
a = np.array([["Delhi", "Bhiwani"], ["amritsar", "kota"]])
b = np.array([["Noida", "Gurgaon"], ["Surat", "Mumbai"]])

print(np.vstack((a,b)))
print()
print(np.hstack((a,b)))

[['Delhi' 'Bhiwani']
 ['amritsar' 'kota']
 ['Noida' 'Gurgaon']
 ['Surat' 'Mumbai']]

[['Delhi' 'Bhiwani' 'Noida' 'Gurgaon']
 ['amritsar' 'kota' 'Surat' 'Mumbai']]


### Copy and view 

In [62]:
# Copy function copy the original array to a new one and will not make any changes in original one

# View will clone the original to other array and will make change in original also if any change makes in clone one.

a = np.array([20,39,45,43])
b = a.copy()
b[1] = 2
print(b)
print(a)

print("View function")

c = np.array([20,39,45,43])
d = c.view()
d[1] = 2
print(c)
print(d)

[20  2 45 43]
[20 39 45 43]
View function
[20  2 45 43]
[20  2 45 43]


In [63]:
# Base function--> to understand if array is related to anyone or not

a = np.array([20,39,45,43])
x = a.copy()
y = a.view()
print(x.base)   #None, as copy make it independent 
print(y.base)    # SHows to which data it is related to

None
[20 39 45 43]
